# Default runtime profile for HHU HILBERT infrastructure / PBS Professional

#directory: /gpfs/scratch/marijon/cocktail
cluster: >-
  qsub
  -A {cluster.account} -l walltime={cluster.run_hrs}:{cluster.run_min}:00
  -l select=1:ncpus={cluster.cores}:mem={cluster.mem_mb}mb
  -N {cluster.name} -o {cluster.output} -e {cluster.error}
cluster-config: etc/hilbert/cluster.json
local-cores: 1
jobs: 60
latency-wait: 300
keep-going: True
keep-incomplete: True
rerun-incomplete: True
restart-times: 0
max-status-checks-per-second: 0.001
use-conda: True
use-envmodules: True
nolock: False
default-resources:
  - mem_per_cpu_mb=32768
  - mem_total_mb=64000
  - runtime_hrs=6
  - runtime_min=59
